### ISSUE TITLE
Remove MongoDict as a dependency

### ISSUE THREAD

**Issue by flavioamieiro** [NAMD/pypln.backend#173]
We've been using MongoDict in our base task as a way to get document attributes from mongodb. This is an easy way to interact with mongodb, but it has an overhead for serializing and deserializing every object that is impacting our performance. We need to use pymongo's api directly to reduce the time we spend getting attributes from mongo and inserting them back.

**Comment by turicas** [comment]
You may use the `codec` parameter on `MongoDict.__init__` to change the default codecs (`pickle.dumps` and `pickle.loads`).

**Comment by fccoelho** [comment]
@turicas , it's not just the serialization costs, but Mongodict makes multiple queries  to  the database as the dict is being updated and those add up to a serious overload, when compared with simple construction of a python dict and a single insert to the database. Moreover, it creates a opaque collection in the database which cannot be inspected on the console.

Here is a simple benchmark code if you are interested: https://gist.github.com/fccoelho/fc77e7f3917b761a258b

**Comment by turicas** [comment]
@fccoelho, ok, you're right: in the case of updating the entries with a high frequency, MongoDict is not the best solution.

**Comment by turicas** [comment]
Just remember MongoDB will fragment its database files if you update data on a high frequency. So probably the best approach will be store the intermediate values and update less often.

**Comment by fccoelho** [comment]
The new  WiredTiger engine does ongoing compaction and reuse of space
automatically. So fragmentation will be  a non-issue once we migrate to
mongodb 3.0.3 and start using the new engine.

best,


On Tue, May 26, 2015 at 10:51 AM, Álvaro Justen <notifications@github.com>
wrote:

> Just remember MongoDB will fragment its database files if you update data
> on a high frequency. So probably the best approach will be store the
> intermediate values and update less often.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NAMD/pypln.backend/issues/173#issuecomment-105531785>.
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by turicas** [comment]
Cool! :-)

**Comment by fccoelho** [comment]
solved
